### ISSUE TITLE
Bug: Failed to parse report-phpunit.xml Cannot read properties of undefined (reading 'passed') 

### ISSUE THREAD

**Issue by fredpalas** [lukejpreston/xunit-viewer#140]
Hello I encounter a bug on version 9 and 10 with parsing my xml, On version 8 works.
Output
```
Failed to parse /home/adrian/projects/munky_pride/report-phpunit.xml 
 Cannot read properties of undefined (reading 'passed') 

file:///home/adrian/.nvm/versions/node/v16.20.0/lib/node_modules/xunit-viewer/src/cli/get-description.js:3
  Object.values(suites.suites).forEach((suite) => {
         ^

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at default (file:///home/adrian/.nvm/versions/node/v16.20.0/lib/node_modules/xunit-viewer/src/cli/get-description.js:3:10)
    at runXunitViewer (file:///home/adrian/.nvm/versions/node/v16.20.0/lib/node_modules/xunit-viewer/xunit-viewer.js:26:25)
    at async default (file:///home/adrian/.nvm/versions/node/v16.20.0/lib/node_modules/xunit-viewer/xunit-viewer.js:37:46)
```

Node 16 and node 18

version xunit-viewer 9 and 10.

xml, I remove other testsuite, fail with one or many.

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="48" assertions="121" errors="0" warnings="0" failures="0" skipped="0" time="6.719176">
    <testsuite name="Project Test Suite" tests="48" assertions="121" errors="0" warnings="0" failures="0" skipped="0" time="6.719176">
      <testsuite name="App\Tests\Feature\Controller\Api\Charger\CreateChargeControllerTest" file="/var/www/tests/Feature/Controller/Api/Charger/CreateChargeControllerTest.php" tests="1" assertions="5" errors="0" warnings="0" failures="0" skipped="0" time="3.007336">
        <testcase name="testShouldCreateAnCharge" class="App\Tests\Feature\Controller\Api\Charger\CreateChargeControllerTest" classname="App.Tests.Feature.Controller.Api.Charger.CreateChargeControllerTest" file="/var/www/tests/Feature/Controller/Api/Charger/CreateChargeControllerTest.php" line="37" assertions="5" time="3.007336"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
```

Thank you, I will be on version 8 until if possible to fix the bug.

**Comment by lukejpreston** [comment]
Thanks for this. I forgot to test nested test suites 😄 

Could you test out v10.3.0 and let me know if it has been fixed for you, please?

**Comment by fredpalas** [comment]
with v10.3.0 works.

Thank you very much.
