### ISSUE TITLE
websockets and file watching

### ISSUE THREAD

**Issue by lukejpreston** [lukejpreston/xunit-viewer#31]
currently, WebSockets do not work anyway

as files change the view should update accordingly, 

add notifications to `Files`

**Comment by AmauryOrtega** [comment]
@lukejpreston First, thanks for your work on this tool. It has been really helpful during my career.

I assume that "add notifications to `Files`" refers to the `--watch` option because at the moment, I can't make it work.

### System information

- node `10.16.3`
- alpine `3.9.4`
- xunit-viewer `5.1.10`

### Steps to reproduce error

```shell
npm install -g xunit-viewer
xunit-viewer --watch --results=tests.xml --port=80
```

When overwriting the content of the `text.xml` file, this error shows up.

```
(node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'testsuites' of null
    at xml2js (/usr/local/lib/node_modules/xunit-viewer/parser/index.js:9:12)
    at Object.parse (/usr/local/lib/node_modules/xunit-viewer/parser/index.js:207:18)
    at files.map.file (/usr/local/lib/node_modules/xunit-viewer/cli/parse-files.js:9:23)
    at Array.map (<anonymous>)
    at Promise (/usr/local/lib/node_modules/xunit-viewer/cli/parse-files.js:6:25)
    at new Promise (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/xunit-viewer/cli/parse-files.js:5:10)
    at resolveFiles.then.files (/usr/local/lib/node_modules/xunit-viewer/cli/start-sockets.js:41:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by lukejpreston** [comment]
not quite, `--watch` in the current version will watch the files for changes and then re-run the xunit viewer, `--port` is the thing which starts a server and combined with `--watch` is meant to do websockets, but the websockets don't really work. What happens when you don't use `--port`?

**Comment by AmauryOrtega** [comment]
@lukejpreston When I don't use the `--port`, the process ends with an `0` exit code and no messages. Same scenario as mentioned before.

**Comment by lukejpreston** [comment]
Try out v6 but this should be working fine now
