### ISSUE TITLE
Nothing test showing in HTML

### ISSUE THREAD

**Issue by luisxkimo** [lukejpreston/xunit-viewer#51]
Hi,

We cannot see anything in html after parse a result file generated with xunit console. Here is an example of results xml file:

```
<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly name="E:\Temp\UnitTests.DLL" configFile="E:\Temp\UnitTests.dll.config" run-date="2019-08-19" run-time="16:42:05" time="0.648" total="5" passed="4" failed="1" skipped="0" environment="64-bit .NET 4.0.30319.42000 [collection-per-class, parallel (28 threads)]" test-framework="xUnit.net 2.4.0.4049">
    <class name="ProjectName.UnitTests.Domain.Audio.AddBugShould" time="0.483" total="5" passed="4" failed="1" skipped="0">
      <test name="ProjectName.UnitTests.Domain.Audio.AddBugShould.CreateAndAddBug_TestName" type="ProjectName.UnitTests.Domain.Audio.AddBugShould" method="CreateAndAddBug_TestName" result="Fail" time="0.4574401">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected boolean to be False, but found True.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Primitives.BooleanAssertions.Be(Boolean expected, String because, Object[] becauseArgs)</stack-trace>
        </failure>
      </test>
      <test name="ProjectName.UnitTests.Domain.Audio.AddBugShould.ThrowException_MethodName2" type="ProjectName.UnitTests.Domain.Audio.AddBugShould" method="ThrowException_MethodName2" result="Pass" time="0.0010112" />
    </class>
  </assembly>
</assemblies>
```

And here is the _xunit console_ command execution:
`xunit.console.exe UnitTests.dll -verbose -xmlv1 "results_xml_v1.xml" -class "ProjectName.UnitTests.Domain.Audio.AddBugShould"`

**Note**: with parameter _-xml_ that generates a new v2 version of XML not works too.

**Comment by lukejpreston** [comment]
I have an issue for this already https://github.com/lukejpreston/xunit-viewer/issues/14

I don't have any examples of using junit 2, can I use this one plus wondering if you could prefab some examples for me which have the following equivalent states from junit 1 `passed`, `skipped` `failure`, `error` and if possible to ass some random properties to the suites + tests?

**Comment by lukejpreston** [comment]
I will close this issue and copy your code to that one for now
