### ISSUE TITLE
xunit-viewer@5.1.12 -  Error: Cannot find module 'clone'

### ISSUE THREAD

**Issue by connected-mhuang** [lukejpreston/xunit-viewer#56]
**How to reproduce:**
```
xunit-viewer --results=report.xml --output=report.html
```

**Expected:**
 - generate report.html file 

**Actual:**
```
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'clone'
Require stack:
- C:\ProgramData\nvm\v12.0.0\node_modules\xunit-viewer\cli\search-suites.js
- C:\ProgramData\nvm\v12.0.0\node_modules\xunit-viewer\cli\start-terminal.js
- C:\ProgramData\nvm\v12.0.0\node_modules\xunit-viewer\cli\index.js
- C:\ProgramData\nvm\v12.0.0\node_modules\xunit-viewer\bin\xunit-viewer
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\ProgramData\nvm\v12.0.0\node_modules\xunit-viewer\cli\search-suites.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
Exited with code 1
```

**Comment by connected-mhuang** [comment]
`npm i -g clone` will solve this issue. But I hope that this package can add `clone` to its dependency list.

**Comment by t1bb4r** [comment]
Same problem. Looks like it was removed here by mistake, https://github.com/lukejpreston/xunit-viewer/pull/54/files#diff-32607347f8126e6534ebc7ebaec4853dL2711-L2715. In the mean time sticking to 5.1.11 is working

**Comment by lukejpreston** [comment]
whoops, should be good in 5.1.13 thanks for spotting that
