### ISSUE TITLE
System-out not displayed when there is a failure

### ISSUE THREAD

**Issue by zeburek** [lukejpreston/xunit-viewer#69]
* node and npm version: 12.3.1, 6.11.3
* xunit viewer version: 6.1.1
* browser: Any
* sample xml: #68 - suites from here

I think the simplest way is to add any message that is present in XML report, but you can do something else

```diff
diff --git a/src/cli/parse.js b/src/cli/parse.js
index 7d4c5be..216c6f5 100644
--- a/src/cli/parse.js
+++ b/src/cli/parse.js
@@ -99,7 +99,9 @@ const extractTests = (output, suite, testcases) => {
     if (typeof testcase !== 'string') {
       const keys = Object.keys(testcase).filter(key => key !== '$' && key !== '_' && key !== 'testcase')
       let status = keys[0]
-      if (status) extractTestMessages(test, testcase[status])
+      keys.forEach((key) => {
+        if (status) extractTestMessages(test, testcase[key])
+      })
       if (status === 'system-out') status = 'passed'
       test.status = status || 'passed'
     }
```

this fix breaks two tests, is it OK?

```diff
FAIL src/cli/get-suites.test.js
  ● Console

    console.log src/cli/get-files.js:11
      IGNORING: /home/OMP/p.khavari/dev/my/xunit-viewer/data/thing.txt
    console.log src/cli/get-suites.js:12
      Failed to parse /home/OMP/p.khavari/dev/my/xunit-viewer/data/invalid.xml 
       Error: Non-whitespace before first tag.
      Line: 0
      Column: 1
      Char: b 
      
    console.log src/cli/get-suites.js:12
      Failed to parse /home/OMP/p.khavari/dev/my/xunit-viewer/data/subfolder/_thingy.xml 
       Cannot read property 'testsuites' of null 
      

  ● get suites

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    @@ -156,10 +156,12 @@
              "-198845521": Object {
                "id": -198845521,
                "messages": Array [
                  "error inner massage 1",
                  "error message prop 1",
    +             "failure inner massage 2",
    +             "failure message prop 2",
                ],
                "name": "error and failure test with messages",
                "status": "error",
                "time": 0,
                "visible": true,
    @@ -317,10 +319,22 @@
                  "Failing step: Тогда Время последней активности изменяется ... failed in 0.004s
      
      INFO:auth.api.requests:Response: 200 GET http://ocs-app.local:8018/idp/ui/login?login_challenge=d6d839a5812c443b86901005c768ffc9 data: <!DOCTYPE html><html><head><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width,minimum-scale=1,initial-scale=1\"/><meta name=\"next-head-count\" content=\"2\"/><link rel=\"preload\" href=\"/idp/ui/_next/static/HkUfFtgP6klFe2fEQqmxy/pages/login.js\" as=\"script\"/><link rel=\"preload\" href=\"/idp/ui/_next/static/HkUfFtgP6klFe2fEQqmxy/pages/_app.js\" as=\"script\"/><link rel=\"preload\" href=\"/idp/ui/_next/static/runtime/webpack-91b117697e716c22a78b.js\" as=\"script\"/><link rel=\"preload\" href=\"/idp/ui/_next/static/chunks/framework.4a6d1274021dea07c0f6.js\" as=\"script\"/><link rel=\"preload\" href=\"/idp/ui/_next/static/chunks/commons.f45713c7aba3ce20097d.js\" as=\"script\"/><link rel=\"preload\" href=\"/idp/ui/_next/static/chunks/6773ad45d0354f4720872cd5ee776c22f13c9a91.0fb260b186eb72f24901.js\" as=\"script\"/><link rel=\"preload\" href=\"/idp/ui/_next/static/chunks/81ba0819ec88dd0bec17c1c438c133cab6a290fa.916a834513a83791b2f0.js\" as=\"script\"/><link rel=\"preload\" href=\"/idp/ui/_next/static/chunks/925ec3a858999a8097194b2c53fbfdb98bfa7494.17176631661852e1c5ef.js\" as=\"script\"/><link rel=\"preload\" href=\"/idp/ui/_next/static/runtime/main-02786df16d94ee682e6c.js\" as=\"script\"/><link rel=\"preload\" href=\"/idp/ui/_next/static/chunks/caafe67f7e62507843c5388d508343f7cf6447b9.5d398491c28c531fda49.js\" as=\"script\"/><link rel=\"preload\" href=\"/idp/ui/_next/static/chunks/8a5cd78cc6f6305e12437f1637a0ac79a4886b95.f0abb74104c271c8cee6.js\" as=\"script\"/></head><body><div id=\"__next\"></div><script id=\"__NEXT_DATA__\" type=\"application/json\"></script><script nomodule=\"\" src=\"/idp/ui/_next/static/runtime/polyfills-ca767adcfe74e5592607.js\"></script><script defer=\"\" data-next-page=\"/login\" src=\"/idp/ui/_next/static/HkUfFtgP6klFe2fEQqmxy/pages/login.js\"></script><script defer=\"\" data-next-page=\"/_app\" src=\"/idp/ui/_next/static/HkUfFtgP6klFe2fEQqmxy/pages/_app.js\"></script><script src=\"/idp/ui/_next/static/runtime/webpack-91b117697e716c22a78b.js\" defer=\"\"></script><script src=\"/idp/ui/_next/static/chunks/framework.4a6d1274021dea07c0f6.js\" defer=\"\"></script><script src=\"/idp/ui/_next/static/chunks/commons.f45713c7aba3ce20097d.js\" defer=\"\"></script><script src=\"/idp/ui/_next/static/chunks/6773ad45d0354f4720872cd5ee776c22f13c9a91.0fb260b186eb72f24901.js\" defer=\"\"></script><script src=\"/idp/ui/_next/static/chunks/81ba0819ec88dd0bec17c1c438c133cab6a290fa.916a834513a83791b2f0.js\" defer=\"\"></script><script src=\"/idp/ui/_next/static/chunks/925ec3a858999a8097194b2c53fbfdb98bfa7494.17176631661852e1c5ef.js\" defer=\"\"></script><script src=\"/idp/ui/_next/static/runtime/main-02786df16d94ee682e6c.js\" defer=\"\"></script><script src=\"/idp/ui/_next/static/chunks/caafe67f7e62507843c5388d508343f7cf6447b9.5d398491c28c531fda49.js\" defer=\"\"></script><script src=\"/idp/ui/_next/static/chunks/8a5cd78cc6f6305e12437f1637a0ac79a4886b95.f0abb74104c271c8cee6.js\" defer=\"\"></script><script src=\"/idp/ui/_next/static/HkUfFtgP6klFe2fEQqmxy/_buildManifest.js\" defer=\"\"></script></body></html>",
                  "2020-02-13T08:57:11+00:00 < 2020-02-13T08:57:11+00:00",
                  "AssertionError",
    +             "@scenario.begin
    + 
    +   @fixture.test_account_with_all_roles
    +   Сценарий: Время последней активности изменяется при обновлении токена для мобильного устройства
    +     Допустим Пользователь входит в мобильное приложение Aurora-market ... passed in 0.160s
    +     И Запоминает время последней активности ... passed in 0.017s
    +     И Проходит 3 секунда ... passed in 3.002s
    +     Когда Обновляется токен ... passed in 0.062s
    +     Тогда Время последней активности изменяется ... failed in 0.004s
    + 
    + @scenario.end
    + --------------------------------------------------------------------------------",
                ],
                "name": "Время последней активности изменяется при обновлении токена для мобильного устройства",
                "status": "failure",
                "time": "3.245495",
                "visible": true,

      14 |   const files = getFiles(logger, { results: path.resolve(__dirname, '../../data') })
      15 |   const suites = await getSuites(logger, files)
    > 16 |   expect(suites).toEqual(expected)
         |                  ^
      17 | })
      18 | 

      at Object.<anonymous> (src/cli/get-suites.test.js:16:18)

FAIL src/cli/parse.test.js
  ● complete multi suites

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    @@ -83,10 +83,12 @@
              "-198845521": Object {
                "id": -198845521,
                "messages": Array [
                  "error inner massage 1",
                  "error message prop 1",
    +             "failure inner massage 2",
    +             "failure message prop 2",
                ],
                "name": "error and failure test with messages",
                "status": "error",
                "time": 0,
                "visible": true,

      12 |     const data = path.join(dataDir, '/test.xml')
      13 |     const result = await parse(fs.readFileSync(data).toString())
    > 14 |     expect(result).toEqual(expected)
         |                    ^
      15 |   })
      16 | 

      at Object.<anonymous> (src/cli/parse.test.js:14:20)
```

**Comment by lukejpreston** [comment]
This looks great! Create a PR and I will merge it, I added an npm script `npm run update` which should update the tests with the new expected values so just run that before you submit it and it should start passing.
